services:
  - type: web
    name: otp-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - fromDatabase: false
        key: EMAIL_ACCOUNT
      - fromDatabase: false
        key: EMAIL_PASSWORD
